### ISSUE TITLE
SCVS-CAN-14 uses "component type" but the standard does not define the term

### ISSUE THREAD

**Issue by garretfick** [OWASP/Software-Component-Verification-Standard#1]
Problem:

As a user of the specification, I need to be able to determine whether I comply with the standard. The term "component type" leaves a lot of possibilities for interpretation. For example, this could mean "3rd party or open source", "development language", among other interpretations.

Recommendation:

Either add a list of definitions (probably the best) or clarify what this means here.

**Comment by stevespringett** [comment]
There's a paragraph about 'Component Type' here: https://www.owasp.org/index.php/Component_Analysis#Component_Type

Component type is also defined in CycloneDX which lists:

- application
-  framework
- library
- operating-system
- device
- file
https://cyclonedx.org/docs/1.1/#type_classification

Currently the term used in SCVS is 'Component Type'. 

Do we want to continue using that term?
Do we want to use 'Component Classification'?
Something else?

**Comment by stevespringett** [comment]
This has been added to the glossary and to the control itself.
