### ISSUE TITLE
SCVS-INV-03 may way to specify machine readable (or add additional requirement)

### ISSUE THREAD

**Issue by garretfick** [OWASP/Software-Component-Verification-Standard#2]
Problem:

It is relatively common that build logs contain information that can be extracted to generating an accurate inventory. However, this is normally difficult to audit.

Recommendation:

Add a new requirement that specifies that the inventory is available in a format that is readily machine readable format (I'm hesitant to specify a particular format).

**Comment by stevespringett** [comment]
Wouldn't this be covered by SBOM or should there be a specific call out to being machine readable so that someone doesn't confuse SBOM with spreadsheet (or whatever)?

**Comment by stevespringett** [comment]
I belive requirement is done.

v1.3 - An accurate inventory of all third-party components is available in a machine-readable format
